### ISSUE TITLE
Product never ended on ebay

### ISSUE THREAD

**Issue by denouche** [PrestaShop/ebay#58]
Hello,

I have a problem with products which are never ended on Ebay once their quantity is 0 or the product is deactivated.

I guess this is due to the first `return $ebay;` in the `endProductOnEbay` function in the `EbaySynchronizer.php` class. Because the function stop the execution and returns, and the rest of the function is never executed, so the product never deleted. 

Thanks in advance for your answer

**Comment by denouche** [comment]
Just saw the code for not multivariation product is just below, sorry

**Comment by denouche** [comment]
Actually the bug is still present, and due the first `return $ebay;` in the `endProductOnEbay` function in the same class. Because the function stop the execution and returns, and the rest of the function is never executed, so the product never deleted.

**Comment by 202-ecommerce** [comment]
Hi,

Thanks for the fix, we included it in version 1.15.5 (to be available early April).
I close the PR as far this repository is not up to date.

Matthieu

**Comment by denouche** [comment]
Ok thx.
Where can I find an up to date repository, in case I want to do another proposal?

**Comment by 202-ecommerce** [comment]
There is no open repo currently, we need to update the current one.

**Comment by denouche** [comment]
OK
Because I adapted the current module to accept auctions instead of direct buys ... Maybe this could inspire you to add this feature to your module?

**Comment by 202-ecommerce** [comment]
I understand your request, but module is more intended for marketplace approach (so no auctions). I will check with eBay at our next product meeting.
