### ISSUE TITLE
Can't sync with ebay.com

### ISSUE THREAD

**Issue by g4b0** [PrestaShop/ebay#59]
After upgrading I get this warning in backend:

> The eBay module currently works for eBay.fr, eBay.it, eBay.co.uk, eBay.pl, eBay.nl and eBay.es

and my products are not synced anymore to ebay.com. Could you please explain why?

**Comment by 202-ecommerce** [comment]
Hi,

Our module is currently not compatible with eBay.com, [read this article about supported countries](https://help.202-ecommerce.com/ebay-for-prestashop-3/overview/overview-and-benefits/supported-countries/).

If you face an issue with a supported country, please sends us complete issue description to our [support portal](https://support.202-ecommerce.com).

Pierre
